version: '3.8'
networks:
  school:


services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - school

  apigateway:
    build: ./apigateway
    container_name: apigateway
    volumes:
      - ./apigateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - school
    depends_on:
      - mongodb
      - apiteachers
      - apistudents

  apiteachers:
    build: ./service_teacher
    container_name: apiteachers
    volumes:
      - ./service_teacher:/usr/app
    depends_on:
      - mongodb
    networks:
      - school
    ports:
      - 3000:3000

  apistudents:
    build: ./service_students
    container_name: apistudents
    volumes:
      - ./service_students:/usr/app
    depends_on:
      - mongodb
    networks:
      - school
    ports:
      - 3001:3001

  front:
    build: ./front
    container_name: front
    depends_on:
      - apiteachers
      - apistudents
    networks:
      - school
    ports:
      - 3010:3010

volumes:
  data:
